name: Deploy ECS Services

on:
  push: 
    branches:
      - master   

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS }}
          aws-secret-access-key: ${{ secrets.SECRET }}
          aws-region: eu-central-1

      - name: Deploy ECS Instances
        run: |
          aws cloudformation deploy \
            --template-file instances.yml \
            --stack-name instances-stack \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Deploy ECS Services
        run: |
          aws cloudformation deploy \
            --template-file services.yml \
            --stack-name services-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides ECSClusterName=kurchuster
      - name: Register EC2 Instances with ECS Cluster
        run: |
          instance_id1="${{ steps.get-instance-ids.outputs.instance_id_1 }}"
          instance_id2="${{ steps.get-instance-ids.outputs.instance_id_2 }}"
          instance_arn1=$(aws ecs describe-container-instances --cluster DeepLearnProject --filter "name=ec2InstanceId,values=${instance_id1}" --query 'containerInstances[0].containerInstanceArn' --output text)
          instance_arn2=$(aws ecs describe-container-instances --cluster DeepLearnProject --filter "name=ec2InstanceId,values=${instance_id2}" --query 'containerInstances[0].containerInstanceArn' --output text)
          aws ecs register-container-instance --cluster DeepLearnProject --container-instance-arn $instance_arn1
          aws ecs register-container-instance --cluster DeepLearnProject --container-instance-arn $instance_arn2
      - name: Fetch stack events
        run: |
          aws cloudformation describe-stack-events --stack-name <your-stack-name>
