name: Deploy ECS Infrastructure
on:
  push:
    branches:
      - master
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS }}
          aws-secret-access-key: ${{ secrets.SECRETS }}
          aws-region: eu-central-1

      - name: Deploy EC2 instances and ECS resources
        run: |
          aws cloudformation create-stack \
            --stack-name EC2InstancesStack \
            --template-file instances.yml 

      - name: Wait for EC2 instances and ECS resources to be created
        run: |
          aws cloudformation wait stack-create-complete \
            --stack-name EC2InstancesStack

      - name: Deploy ECS cluster and landing service
        run: |
          aws cloudformation create-stack \
            --stack-name ECSStack \
            --template-file services.yml

      - name: Wait for ECS cluster and landing service to be created
        run: |
          aws cloudformation wait stack-create-complete \
            --stack-name ECSStack
